export const SUPPORTED_LANGUAGES = {
  'C#': 10,
  'C' : 7,
  'C++' : 7,
  'CLOJURE' : 2,
  'JAVA' : 8,
  'GO' : 6,
  'JAVASCRIPT' : 4,
  'PHP' : 3,
  'PYTHON' : 0,
  'PYTHON3' : 15,
  'RUBY' : 1,
  'SCALA' : 5,
  'VB.NET' : 9,
  'BASH' : 11,
  'OBJECTIVE-C' : 12,
  'MYSQL' : 13,
  'PERL' : 14,
  'RUST' : 15
};
