import 'bootstrap/dist/css/bootstrap.min.css';
import 'font-awesome/css/font-awesome.min.css';
import 'react-bootstrap-switch/dist/css/bootstrap3/react-bootstrap-switch.min.css';
import 'rc-slider/assets/index.css';
import 'react-big-calendar/lib/css/react-big-calendar.css';
import 'react-joyride/lib/react-joyride-compiled.css';
import './styles/main.scss';
import './styles/colors.scss';
import './src/dev_client';
